### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by duburcqa** [intel-isl/LMRS#1]
Hi !

I was looking to your implement but I have not tested it yet. It seems that the file `random_search/synthetic_environment.py` is missing but required [here](https://github.com/intel-isl/LMRS/blob/d81a0c0d697bc415b44396034559e25e4ead2ede/random_search/online_learner.py#L7). Also, the method `update_variance_reduced` of `MujocoRandomSearchLearned` is called [here](https://github.com/intel-isl/LMRS/blob/d81a0c0d697bc415b44396034559e25e4ead2ede/random_search/mujoco_random_search_learned.py#L356) but undefined.

Best,
Alexis

**Comment by ozansener** [comment]
I added the missing file. Variance reduced version is not shared yet, so I removed the option
